apiVersion: v1
kind: Service
metadata:
 name: project1-elevendevops-service
 labels:
   app: my-app1
spec:
 type: NodePort
 ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
